// Code generated by goctl. DO NOT EDIT.
// Source: usercenter.proto

package server

import (
	"context"

	"homestay/app/usercenter/cmd/rpc/internal/logic"
	"homestay/app/usercenter/cmd/rpc/internal/svc"
	"homestay/app/usercenter/cmd/rpc/user_pb"
)

type UsercenterServer struct {
	svcCtx *svc.ServiceContext
	user_pb.UnimplementedUsercenterServer
}

func NewUsercenterServer(svcCtx *svc.ServiceContext) *UsercenterServer {
	return &UsercenterServer{
		svcCtx: svcCtx,
	}
}

func (s *UsercenterServer) Login(ctx context.Context, in *user_pb.LoginReq) (*user_pb.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UsercenterServer) Register(ctx context.Context, in *user_pb.RegisterReq) (*user_pb.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UsercenterServer) GetUserInfo(ctx context.Context, in *user_pb.GetUserInfoReq) (*user_pb.GetUserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UsercenterServer) GetUserAuthKey(ctx context.Context, in *user_pb.GetUserAuthKeyReq) (*user_pb.GetUserAuthKeyResp, error) {
	l := logic.NewGetUserAuthKeyLogic(ctx, s.svcCtx)
	return l.GetUserAuthKey(in)
}

func (s *UsercenterServer) GetUserAuthByUserId(ctx context.Context, in *user_pb.GetUserAuthByUserIdReq) (*user_pb.GetUserAuthByUserIdResp, error) {
	l := logic.NewGetUserAuthByUserIdLogic(ctx, s.svcCtx)
	return l.GetUserAuthByUserId(in)
}

func (s *UsercenterServer) GenToken(ctx context.Context, in *user_pb.GenTokenReq) (*user_pb.GenTokenResp, error) {
	l := logic.NewGenTokenLogic(ctx, s.svcCtx)
	return l.GenToken(in)
}
